config/routes.rb
Rails.application.routes.draw do
  get "users/search"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "search" => "users#search", as: :search_users

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    if params[:search].present?
      @time1 = Benchmark.realtime do
        @user1 = User.find_by username: params[:search]
      end
      @time2 = Benchmark.realtime do
        @user2 = User.find_by login: params[:search]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Demo Indexes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/search.html.slim
h1 Search
= form_tag search_users_path, method: :get do
  p
    = text_field_tag :search, params[:search]
    = submit_tag "Search", name: nil

- if params[:search]
  h2 Results
  table[border="1"]
    thead
      tr
        th With index
        th Without index
    tbody
      tr
        td
          - if @user1
            dl
              dt ID
              dd= @user1.id
              dt Name
              dd= @user1.full_name
              dt Email
              dd= @user1.email
              dt Username
              dd= @user1.username
              dt Login
              dd= @user1.login
              dt Created at
              dd= @user1.created_at
        td
          - if @user2
            dl
              dt ID
              dd= @user2.id
              dt Name
              dd= @user2.full_name
              dt Email
              dd= @user2.email
              dt Username
              dd= @user2.username
              dt Login
              dd= @user2.login
              dt Created at
              dd= @user2.created_at
      tr
        td= @time1
        td= @time2